site_name: Learn Network
site_url: https://doc-dao.github.io/

plugins:
  - search

theme:
  name: material


nav:
    - Home: index.md
    - About: about.md
    - OVS:
        - Ref: ovs/ref.md
        - DeepDive: ovs/dive.md
