site_name: Learn Network
site_url: https://doc-dao.github.io/

plugins:
  - search

theme:
  name: material


nav:
    - Home: index.md
    - About: about.md
    - Software:
        - Flask: softwares/flask.md
    - OVS:
        - Ref: ovs/ref.md
        - DeepDive: ovs/dive.md
    - Distribution:
        - All: distribution/all.md
    - Network:
        - Basic:
            - DataStructures: network/basic/datastructures.md
            - ALL: network/basic/all.md
            - IP: network/basic/ip.md
            - TCP: network/basic/tcp.md
        - Overlay:
            - VXLAN: network/overlay/vxlan.md
            - GENEVE: network/overlay/geneve.md
        - Books:
            - Linux Network Internals:
                - Notes: network/books/linux-network-internals/notes.md
                - Functions: network/books/linux-network-internals/interfaces.md
        - Research:
            - TCP: network/research/tcp.md
